dist: xenial
sudo: required

language: node_js

node_js:
  - "11"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

install: yarn install --prod=false

script: yarn build-prod
  
