dist: xenial
sudo: required

language: node_js

node_js:
  - "11"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

before_install:
  - yarn global add @angular/cli
  - yarn global add yalc

script:
  - cd ~ && git clone https://github.com/dhlab-basel/Knora-ui.git && cd Knora-ui && yarn install --prod=false && yarn build-lib-prod && yarn yalc-publish
  - cd $TRAVIS_BUILD_DIR && yarn install --prod=false
  - yalc remove --all && yarn yalc-add-modules
  - yarn build-prod
  
