dist: trusty
sudo: required

language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  global:
    - CXX=g++-4.9

install: export CXX="g++-4.9"

before_script:
  - yarn global add @angular/cli
  - yarn install
  - yarn add global yalc
  - cd ~ && git clone https://github.com/dhlab-basel/Knora-ui.git && cd Knora-ui && yarn build-lib-prod && yarn yalc-publish

script:
  - yarn yalc-add-modules
  - yarn build-prod
  
